name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install and start backend
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build backend
        run: mvn package -DskipTests
        working-directory: backend
      - name: Start backend
        run: nohup mvn spring-boot:run &
        working-directory: backend

      # Install frontend dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
        # working-directory not needed, default is repo root
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
